namespace MasterOfPuppets.Ipc;

public enum IpcMessageType {
    Hello = 1,
    Bye,
    Acknowledge,
    RunMacro,
    StopMacroExecution,
    PauseMacroExecution,
    ResumeMacroExecution,
    StopMovement,
    SyncConfiguration,
    RefreshCommands,
    ExecuteTextCommand,
    ExecuteActionCommand,
    ExecuteGeneralActionCommand,
    ExecuteItemCommand,
    ExecuteTargetMyTarget,
    ExecuteInteractWithMyTarget,
    ExecuteInteractWithTarget,
    ExecuteMoveToMyTarget,
    ExecuteStackOnMe,
    ExecuteToggleWalking,
    ExecuteTargetClear,
    ExecuteAbandonDuty,
    EnqueueMacroActions,
    EnqueueCharacterMacroActions,
    SetGameSettingsObjectQuantity,
    ExecuteChangeGearset,
    SetWindowTitle,
    ExecuteFormation,
    RequestEmoteList,
    EmoteList,
    KeyboardBroadcastToggle,
    KeyboardInput,
}
