using System;
using System.Collections.Generic;
using System.Linq;

using Dalamud.Game.Config;
using Dalamud.Memory;

using FFXIVClientStructs.FFXIV.Client.System.Framework;
using FFXIVClientStructs.FFXIV.Client.UI.Misc;
using FFXIVClientStructs.FFXIV.Common.Configuration;

// using CSConfigType = FFXIVClientStructs.FFXIV.Common.Configuration.ConfigType;

namespace MasterOfPuppets;

public static class GameSettingsManager {
    private static List<string>? _allSettingsKeys;

    public static unsafe void GetSettings() {
        var gameConfig = Framework.Instance()->SystemConfig.SystemConfigBase.ConfigBase.ConfigEntry;
        if (gameConfig == null) return;

        uint displayObjectLimit = gameConfig[(int)ConfigOption.DisplayObjectLimitType].Value.UInt;
        uint displayObjectLimit2 = gameConfig[(int)ConfigOption.DisplayObjectLimitType2].Value.UInt;
        // keep game pad enabled when client is inactive
        var alwaysInput = gameConfig[(int)ConfigOption.AlwaysInput].Value.UInt;

        DalamudApi.PluginLog.Warning($"DisplayObjectLimit {displayObjectLimit}");
        DalamudApi.PluginLog.Warning($"DisplayObjectLimit2 {displayObjectLimit2}");
        DalamudApi.PluginLog.Warning($"alwaysInput {alwaysInput}");
        // gameConfig[(int)ConfigOption.DisplayObjectLimitType].SetValueUInt((uint)DisplayObjectLimit.Maximum);
    }

    public static unsafe List<string> GetAllGameSettingsKeys() {
        if (_allSettingsKeys != null) return _allSettingsKeys;

        var keys = new List<string>();
        void extract(ConfigBase* configBase) {
            var e = configBase->ConfigEntry;
            for (var i = 0U; i < configBase->ConfigCount; i++, e++) {
                var ptr = (byte*)e->Name;
                if (ptr != null) {
                    var keyName = MemoryHelper.ReadStringNullTerminated((IntPtr)ptr);
                    if (AllowedSettingsKeys.Contains(keyName)) {
                        keys.Add(keyName);
                    }
                }
            }
        }
        extract(&Framework.Instance()->SystemConfig.SystemConfigBase.ConfigBase);
        extract(&Framework.Instance()->SystemConfig.UiConfig);
        extract(&Framework.Instance()->SystemConfig.UiControlConfig);
        _allSettingsKeys = keys.Distinct().OrderBy(k => k).ToList();
        return _allSettingsKeys;
    }

    public static unsafe void DebugLogUnmappedKeys() {
        var unmappedCount = 0;
        void check(ConfigBase* configBase) {
            var e = configBase->ConfigEntry;
            for (var i = 0U; i < configBase->ConfigCount; i++, e++) {
                var ptr = (byte*)e->Name;
                if (ptr != null) {
                    var keyName = MemoryHelper.ReadStringNullTerminated((IntPtr)ptr);
                    if (!AllowedSettingsKeys.Contains(keyName)) {
                        DalamudApi.PluginLog.Debug($"Unmapped Game Setting Key: {keyName}");
                        unmappedCount++;
                    }
                }
            }
        }
        check(&Framework.Instance()->SystemConfig.SystemConfigBase.ConfigBase);
        check(&Framework.Instance()->SystemConfig.UiConfig);
        check(&Framework.Instance()->SystemConfig.UiControlConfig);
        DalamudApi.PluginLog.Warning($"Finished logging unmapped keys. Total: {unmappedCount}");
    }

    public static unsafe GameSettingsProfile CreateProfile(string name, HashSet<string> allowedKeys) {
        var profile = new GameSettingsProfile { Name = name };
        profile.System = SnapshotConfigBase(&Framework.Instance()->SystemConfig.SystemConfigBase.ConfigBase, allowedKeys);
        profile.Ui = SnapshotConfigBase(&Framework.Instance()->SystemConfig.UiConfig, allowedKeys);
        profile.UiControl = SnapshotConfigBase(&Framework.Instance()->SystemConfig.UiControlConfig, allowedKeys);
        return profile;
    }

    private static unsafe GameSettingsSnapshot SnapshotConfigBase(ConfigBase* configBase, HashSet<string> allowedKeys) {
        var snapshot = new GameSettingsSnapshot();
        var e = configBase->ConfigEntry;
        for (var i = 0U; i < configBase->ConfigCount; i++, e++) {
            var ptr = (byte*)e->Name;
            if (ptr == null) continue;
            var name = MemoryHelper.ReadStringNullTerminated((IntPtr)ptr);
            if (!AllowedSettingsKeys.Contains(name)) continue;
            if (!allowedKeys.Contains(name)) continue;

            if (e->Type == 2) snapshot.UIntSettings[name] = e->Value.UInt;
            else if (e->Type == 3) snapshot.FloatSettings[name] = e->Value.Float;
            else if (e->Type == 4 && e->Value.String != null) snapshot.StringSettings[name] = e->Value.String->ToString();
        }
        return snapshot;
    }

    public static unsafe void ApplyProfile(GameSettingsProfile profile, HashSet<string> allowedKeys) {
        ApplySnapshot(&Framework.Instance()->SystemConfig.SystemConfigBase.ConfigBase, profile.System, allowedKeys);
        ApplySnapshot(&Framework.Instance()->SystemConfig.UiConfig, profile.Ui, allowedKeys);
        ApplySnapshot(&Framework.Instance()->SystemConfig.UiControlConfig, profile.UiControl, allowedKeys);
    }

    private static unsafe void ApplySnapshot(ConfigBase* configBase, GameSettingsSnapshot snapshot, HashSet<string> allowedKeys) {
        var e = configBase->ConfigEntry;
        for (var i = 0U; i < configBase->ConfigCount; i++, e++) {
            var ptr = (byte*)e->Name;
            if (ptr == null) continue;
            var name = MemoryHelper.ReadStringNullTerminated((IntPtr)ptr);
            if (!AllowedSettingsKeys.Contains(name)) continue;
            if (!allowedKeys.Contains(name)) continue;

            if (e->Type == 2 && snapshot.UIntSettings.TryGetValue(name, out var uval)) e->SetValueUInt(uval);
            else if (e->Type == 3 && snapshot.FloatSettings.TryGetValue(name, out var fval)) e->SetValueFloat(fval);
            else if (e->Type == 4 && snapshot.StringSettings.TryGetValue(name, out var sval)) e->SetValueString(sval);
        }
    }

    public static SettingsDisplayObjectLimitType GetDisplayObjectLimit() {
        DalamudApi.GameConfig.TryGet(SystemConfigOption.DisplayObjectLimitType2, out uint displayObjectLimitType2);
        // DalamudApi.PluginLog.Debug($"displayObjectLimitType2 {displayObjectLimitType2}");
        return (SettingsDisplayObjectLimitType)displayObjectLimitType2;
    }

    public static void SetDisplayObjectLimit(SettingsDisplayObjectLimitType displayObjectLimitType) {
        DalamudApi.GameConfig.Set(SystemConfigOption.DisplayObjectLimitType2, (uint)displayObjectLimitType);
    }

    public static void SetAutoFaceTarget(uint value) {
        if (value is 0u or 1u) {
            DalamudApi.GameConfig.Set(UiControlOption.AutoFaceTargetOnAction, value);
        }
    }

    public static void SetAlwaysInput(uint value) {
        if (value is 0u or 1u) {
            DalamudApi.GameConfig.Set(SystemConfigOption.AlwaysInput, value);
        }
    }

    public static void SetSoundMaster(uint value) {
        // 0 = enabled
        // 1 = muted
        if (value is 0u or 1u) {
            DalamudApi.GameConfig.Set(SystemConfigOption.IsSndMaster, value);
            // DalamudApi.GameConfig.System.Set("IsSndMaster", value);
            // DalamudApi.GameConfig.System.GetUInt("IsSndMaster");
        }
    }

    // public static void GetDisplayObjectLimitType()
    // {
    //     DalamudApi.GameConfig.TryGet(SystemConfigOption.DisplayObjectLimitType, out uint displayObjectLimitType);
    //     DalamudApi.PluginLog.Warning($"displayObjectLimitType {displayObjectLimitType}");
    // }

    // public static void SetDisplayObjectLimitType(uint displayObjectLimitType)
    // {
    //     DalamudApi.GameConfig.Set(SystemConfigOption.DisplayObjectLimitType, displayObjectLimitType);
    // }


    // DalamudApi.GameConfig.UiConfigChanged += OnConfigChange;
    //     DalamudApi.GameConfig.UiControlChanged += OnConfigChange;
    //     var MoveMode = DalamudApi.GameConfig.UiControl.GetUInt("MoveMode");
    // var PadMode = DalamudApi.GameConfig.UiConfig.GetUInt("PadMode");
    // DalamudApi.GameConfig.UiControl.Set("MoveMode", 0);
    //     DalamudApi.GameConfig.UiConfig.Set("PadMode", 0);
    //     DalamudApi.GameConfig.UiConfig.Set("PadMode", PadMode);
    //     DalamudApi.GameConfig.UiControl.Set("MoveMode", MoveMode);

    public static void EnableDebug() {
        DalamudApi.GameConfig.UiConfigChanged += OnUiConfigChanged;
        DalamudApi.GameConfig.UiControlChanged += OnUiControlChanged;
        DalamudApi.GameConfig.SystemChanged += OnSystemConfigChange;
    }

    public static void DisableDebug() {
        DalamudApi.GameConfig.UiConfigChanged -= OnUiConfigChanged;
        DalamudApi.GameConfig.UiControlChanged -= OnUiControlChanged;
        DalamudApi.GameConfig.SystemChanged -= OnSystemConfigChange;
    }

    private static void OnUiConfigChanged(object? sender, ConfigChangeEvent e) {
        var option = e.Option;
        var optionName = e.Option.ToString();

        DalamudApi.PluginLog.Warning($"UiConfigChanged: {option}");

        try {
            var value = DalamudApi.GameConfig.UiConfig.GetUInt(optionName);
            DalamudApi.PluginLog.Warning($"{optionName} [{option}] (UInt) = {value}");
            return;
        } catch { }

        try {
            var value = DalamudApi.GameConfig.UiConfig.GetFloat(optionName);
            DalamudApi.PluginLog.Warning($"{optionName} [{option}] (Float) = {value}");
            return;
        } catch { }

        try {
            var value = DalamudApi.GameConfig.UiConfig.GetString(optionName);
            DalamudApi.PluginLog.Warning($"{optionName} [{option}] (String) = {value}");
            return;
        } catch { }
    }

    private static void OnUiControlChanged(object? sender, ConfigChangeEvent e) {
        var option = e.Option;
        var optionName = e.Option.ToString();

        DalamudApi.PluginLog.Warning($"UiControlChanged: {option}");

        try {
            var value = DalamudApi.GameConfig.UiControl.GetUInt(optionName);
            DalamudApi.PluginLog.Warning($"{optionName} [{option}] (UInt - Control) = {value}");
            return;
        } catch { }
    }

    private static void OnSystemConfigChange(object? sender, ConfigChangeEvent e) {
        var option = e.Option;
        var optionName = e.Option.ToString();

        DalamudApi.PluginLog.Warning($"SystemChanged: {optionName} [{option}]");

        // try {
        //     DalamudApi.GameConfig.TryGet(SystemConfigOption.?, out uint value);
        //     DalamudApi.PluginLog.Warning($"{optionName} [{option}] (UInt - Control) = {value}");
        //     return;
        // } catch { }
    }

    public static readonly HashSet<string> DefaultGameSettingsProfileKeys = new(StringComparer.OrdinalIgnoreCase) {
        "Refreshrate",
        "Fps",
        "FPSInActive",
        "AntiAliasing",
        "CharaLight",
        "TextureFilterQuality",
        "TextureAnisotropicQuality",
        "SSAO",
        "Glare",
        "DistortionWater",
        "DepthOfField",
        "RadialBlur",
        "Vignetting",
        "GrassQuality",
        "TranslucentQuality",
        "ShadowVisibilityType",
        "ShadowSoftShadowType",
        "ShadowTextureSizeType",
        "ShadowCascadeCountType",
        "LodType",
        "StreamingType",
        "GeneralQuality",
        "OcclusionCulling",
        "ShadowLOD",
        "PhysicsType",
        "MapResolution",
        "ShadowVisibilityTypeSelf",
        "ShadowVisibilityTypeParty",
        "ShadowVisibilityTypeOther",
        "ShadowVisibilityTypeEnemy",
        "PhysicsTypeSelf",
        "PhysicsTypeParty",
        "PhysicsTypeOther",
        "PhysicsTypeEnemy",
        "ReflectionType",
        "IsSoundDisable",
        "IsSoundAlways",
        "IsSoundBgmAlways",
        "IsSoundSeAlways",
        "IsSoundVoiceAlways",
        "IsSoundSystemAlways",
        "IsSoundEnvAlways",
        "IsSoundPerformAlways",
        "AlwaysInput",
        "PadMode",
        "EnablePsFunction",
        "WaterWet",
        "DisplayObjectLimitType",
        "WindowDispNum",
        "AntiAliasing_DX11",
        "TextureFilterQuality_DX11",
        "TextureAnisotropicQuality_DX11",
        "SSAO_DX11",
        "Glare_DX11",
        "DistortionWater_DX11",
        "DepthOfField_DX11",
        "RadialBlur_DX11",
        "Vignetting_DX11",
        "GrassQuality_DX11",
        "TranslucentQuality_DX11",
        "ShadowSoftShadowType_DX11",
        "ShadowTextureSizeType_DX11",
        "ShadowCascadeCountType_DX11",
        "LodType_DX11",
        "OcclusionCulling_DX11",
        "ShadowLOD_DX11",
        "MapResolution_DX11",
        "ShadowVisibilityTypeSelf_DX11",
        "ShadowVisibilityTypeParty_DX11",
        "ShadowVisibilityTypeOther_DX11",
        "ShadowVisibilityTypeEnemy_DX11",
        "PhysicsTypeSelf_DX11",
        "PhysicsTypeParty_DX11",
        "PhysicsTypeOther_DX11",
        "PhysicsTypeEnemy_DX11",
        "ReflectionType_DX11",
        "WaterWet_DX11",
        "ParallaxOcclusion_DX11",
        "Tessellation_DX11",
        "GlareRepresentation_DX11",
        "DynamicRezoThreshold",
        "GraphicsRezoScale",
        "GraphicsRezoUpscaleType",
        "GrassEnableDynamicInterference",
        "ShadowBgLOD",
        "TextureRezoType",
        "ShadowLightValidType",
        "DynamicRezoEnableCutScene",
        "AutoAfkSwitchingTime",
        "DisplayObjectLimitType2",
        "DisplayHouseIndoorPcLimitType",
        "FPSDownAFK",
        "IdlingCameraAFK",
        "CameraZoom",
        "Is3DAudio",
        "BattleEffect",
        "BGEffect",
        "FellowshipShowNewNotice",
        "CutsceneMovieOpening",
        "SoundMaster",
        "SoundBgm",
        "SoundSe",
        "SoundVoice",
        "SoundEnv",
        "SoundSystem",
        "SoundPerform",
        "SoundPlayer",
        "SoundParty",
        "SoundOther",
        "IsSndMaster",
        "IsSndBgm",
        "IsSndSe",
        "IsSndVoice",
        "IsSndEnv",
        "IsSndSystem",
        "IsSndPerform",
        "SoundDolby",
        "SoundMicpos",
        "SoundChocobo",
        "SoundFieldBattle",
        "SoundCfTimeCount",
        "SoundHousing",
        "SoundEqualizerType",
        "CameraProductionOfAction",
        "FPSCameraInterpolationType",
        "FPSCameraVerticalInterpolation",
        "LegacyCameraCorrectionFix",
        "LegacyCameraType",
        "EventCameraAutoControl",
        "CameraLookBlinkType",
        "EgiMirageTypeGaruda",
        "EgiMirageTypeTitan",
        "EgiMirageTypeIfrit",
        "BahamutSize",
        "PetMirageTypeCarbuncleSupport",
        "PhoenixSize",
        "GarudaSize",
        "TitanSize",
        "IfritSize",
        "SolBahamutSize",
        "PetMirageTypeFairy",
        "TimeMode",
        "Time12",
        "TimeEorzea",
        "TimeLocal",
        "TimeServer",
        // "AutoFaceTargetOnAction",
    };

    public static readonly HashSet<string> AllowedSettingsKeys = new(StringComparer.OrdinalIgnoreCase) {
        // System -> uint
        // "GuidVersion",
        // "ConfigVersion",
        // "Language",
        // "Region",
        // "UPnP",
        // "Port",
        // "LastLogin0",
        // "LastLogin1",
        // "WorldId",
        // "ServiceIndex",
        // "ScreenLeft",
        // "ScreenTop",
        // "ScreenWidth",
        // "ScreenHeight",

        "ScreenMode",
        "FullScreenWidth",
        "FullScreenHeight",
        "Refreshrate",
        "Fps",
        "AntiAliasing",
        "FPSInActive",
        "ResoMouseDrag",
        "MouseOpeLimit",

        // "LangSelectSub",
        "Gamma",
        "UiBaseScale",
        "CharaLight",
        "UiHighScale",
        "TextureFilterQuality",
        "TextureAnisotropicQuality",
        "SSAO",
        "Glare",
        "DistortionWater",
        "DepthOfField",
        "RadialBlur",
        "Vignetting",
        "GrassQuality",
        "TranslucentQuality",
        "ShadowVisibilityType",
        "ShadowSoftShadowType",
        "ShadowTextureSizeType",
        "ShadowCascadeCountType",
        "LodType",
        "StreamingType",
        "GeneralQuality",
        "OcclusionCulling",
        "ShadowLOD",
        "PhysicsType",
        "MapResolution",
        "ShadowVisibilityTypeSelf",
        "ShadowVisibilityTypeParty",
        "ShadowVisibilityTypeOther",
        "ShadowVisibilityTypeEnemy",
        "PhysicsTypeSelf",
        "PhysicsTypeParty",
        "PhysicsTypeOther",
        "PhysicsTypeEnemy",
        "ReflectionType",
        "ScreenShotImageType",
        "IsSoundDisable",
        "IsSoundAlways",
        "IsSoundBgmAlways",
        "IsSoundSeAlways",
        "IsSoundVoiceAlways",
        "IsSoundSystemAlways",
        "IsSoundEnvAlways",
        "IsSoundPerformAlways",
        "PadGuid",
        "AlwaysInput",
        "ForceFeedBack",
        "PadPovInput",
        "PadMode",
        "PadAvailable",
        "PadReverseConfirmCancel",
        "PadSelectButtonIcon",
        "PadMouseMode",
        "TextPasteEnable",
        "EnablePsFunction",
        "WaterWet",
        "DisplayObjectLimitType",
        "WindowDispNum",
        "AntiAliasing_DX11",
        "TextureFilterQuality_DX11",
        "TextureAnisotropicQuality_DX11",
        "SSAO_DX11",
        "Glare_DX11",
        "DistortionWater_DX11",
        "DepthOfField_DX11",
        "RadialBlur_DX11",
        "Vignetting_DX11",
        "GrassQuality_DX11",
        "TranslucentQuality_DX11",
        "ShadowSoftShadowType_DX11",
        "ShadowTextureSizeType_DX11",
        "ShadowCascadeCountType_DX11",
        "LodType_DX11",
        "OcclusionCulling_DX11",
        "ShadowLOD_DX11",
        "MapResolution_DX11",
        "ShadowVisibilityTypeSelf_DX11",
        "ShadowVisibilityTypeParty_DX11",
        "ShadowVisibilityTypeOther_DX11",
        "ShadowVisibilityTypeEnemy_DX11",
        "PhysicsTypeSelf_DX11",
        "PhysicsTypeParty_DX11",
        "PhysicsTypeOther_DX11",
        "PhysicsTypeEnemy_DX11",
        "ReflectionType_DX11",
        "WaterWet_DX11",
        "ParallaxOcclusion_DX11",
        "Tessellation_DX11",
        "GlareRepresentation_DX11",
        "DynamicRezoThreshold",
        "GraphicsRezoScale",
        "GraphicsRezoUpscaleType",
        "GrassEnableDynamicInterference",
        "ShadowBgLOD",
        "TextureRezoType",
        "ShadowLightValidType",
        "DynamicRezoEnableCutScene",
        "UiSystemEnlarge",
        "SoundPadSeType",
        "SoundPad",
        "IsSoundPad",
        "TouchPadMouse",
        "TouchPadCursorSpeed",
        "TouchPadButtonExtension",
        "TouchPadButton_Left",
        "TouchPadButton_Right",
        "RemotePlayRearTouchpadEnable",
        "SupportButtonAutorunEnable",
        "R3ButtonWindowScalingEnable",
        "AutoAfkSwitchingTime",
        "AutoChangeCameraMode",
        // "MsqProgress",
        "PromptConfigUpdate",
        // "TitleScreenType",
        "DisplayObjectLimitType2",
        "DisplayHouseIndoorPcLimitType",
        "AccessibilitySoundVisualEnable",
        "AccessibilitySoundVisualDispSize",
        "AccessibilitySoundVisualPermeabilityRate",
        "AccessibilityColorBlindFilterEnable",
        "AccessibilityColorBlindFilterType",
        "AccessibilityColorBlindFilterStrength",
        "MouseAutoFocus",
        "FPSDownAFK",
        "IdlingCameraAFK",
        // "FirstConfigBackup",
        "CameraZoom",
        "DynamicAroundRangeMode",
        "DynamicRezoType",
        "Is3DAudio",
        "BattleEffect",
        "BGEffect",
        "ColorThemeType",
        "SystemMouseOperationSoftOn",
        "SystemMouseOperationTrajectory",
        "SystemMouseOperationCursorScaling",
        "HardwareCursorSize",
        "UiAssetType",
        "FellowshipShowNewNotice",
        // "CutsceneMovieVoice",
        // "CutsceneMovieCaption",
        "CutsceneMovieOpening",
        "SoundMaster",
        "SoundBgm",
        "SoundSe",
        "SoundVoice",
        "SoundEnv",
        "SoundSystem",
        "SoundPerform",
        "SoundPlayer",
        "SoundParty",
        "SoundOther",
        "IsSndMaster",
        "IsSndBgm",
        "IsSndSe",
        "IsSndVoice",
        "IsSndEnv",
        "IsSndSystem",
        "IsSndPerform",
        "SoundDolby",
        "SoundMicpos",
        "SoundChocobo",
        "SoundFieldBattle",
        "SoundCfTimeCount",
        "SoundHousing",
        "SoundEqualizerType",

        // System -> float
        "DeadArea",
        "MouseSpeed",

        // System -> string
        // "DktSessionId",
        // "MainAdapter",
        // "InstanceGuid",
        // "ProductGuid",
        // "Alias",
        // "ActiveInstanceGuid",
        // "ActiveProductGuid",
        // "ScreenShotDir",
        "PadButton_L2",
        "PadButton_R2",
        "PadButton_L1",
        "PadButton_R1",
        "PadButton_Triangle",
        "PadButton_Circle",
        "PadButton_Cross",
        "PadButton_Square",
        "PadButton_Select",
        "PadButton_Start",
        "PadButton_LS",
        "PadButton_RS",
        "PadButton_L3",
        "PadButton_R3",

        // Ui -> uint
        // "BattleEffectSelf",
        // "BattleEffectParty",
        // "BattleEffectOther",
        // "BattleEffectPvPEnemyPc",
        // "PadMode",
        "WeaponAutoPutAway",
        "WeaponAutoPutAwayTime",
        "LipMotionType",
        "CameraProductionOfAction",
        "FPSCameraInterpolationType",
        "FPSCameraVerticalInterpolation",
        "LegacyCameraCorrectionFix",
        "LegacyCameraType",
        "EventCameraAutoControl",
        "CameraLookBlinkType",
        "IdleEmoteTime",
        "IdleEmoteRandomType",
        "CutsceneSkipIsShip",
        "CutsceneSkipIsContents",
        "CutsceneSkipIsHousing",
        "PetTargetOffInCombat",
        "GroundTargetFPSPosX",
        "GroundTargetFPSPosY",
        "GroundTargetTPSPosX",
        "GroundTargetTPSPosY",
        "TargetDisableAnchor",
        "TargetCircleClickFilterEnableNearestCursor",
        "TargetEnableMouseOverSelect",
        "GroundTargetCursorCorrectType",
        "GroundTargetActionExcuteType",
        "AutoNearestTarget",
        "AutoNearestTargetType",
        "RightClickExclusionPC",
        "RightClickExclusionBNPC",
        "RightClickExclusionMinion",
        "EnableMoveTiltCharacter",
        "EnableMoveTiltMountGround",
        "EnableMoveTiltMountFly",
        "TurnSpeed",
        "FootEffect",
        // "LegacySeal",
        "GBarrelDisp",
        "EgiMirageTypeGaruda",
        "EgiMirageTypeTitan",
        "EgiMirageTypeIfrit",
        "BahamutSize",
        "PetMirageTypeCarbuncleSupport",
        "PhoenixSize",
        "GarudaSize",
        "TitanSize",
        "IfritSize",
        "SolBahamutSize",
        "PetMirageTypeFairy",
        "TimeMode",
        "Time12",
        "TimeEorzea",
        "TimeLocal",
        "TimeServer",
        // "ActiveLS_H",
        // "ActiveLS_L",

        "HotbarLock",
        "HotbarDispRecastTime",
        "HotbarCrossContentsActionEnableInput",
        "HotbarDispRecastTimeDispType",
        "ExHotbarChangeHotbar1",

        // "HotbarCommon01",
        // "HotbarCommon02",
        // "HotbarCommon03",
        // "HotbarCommon04",
        // "HotbarCommon05",
        // "HotbarCommon06",
        // "HotbarCommon07",
        // "HotbarCommon08",
        // "HotbarCommon09",
        // "HotbarCommon10",
        // "HotbarCrossCommon01",
        // "HotbarCrossCommon02",
        // "HotbarCrossCommon03",
        // "HotbarCrossCommon04",
        // "HotbarCrossCommon05",
        // "HotbarCrossCommon06",
        // "HotbarCrossCommon07",
        // "HotbarCrossCommon08",
        "HotbarCrossHelpDisp",
        "HotbarCrossOperation",
        "HotbarCrossDisp",
        "HotbarCrossLock",
        "HotbarCrossUsePadGuide",
        // "HotbarCrossActiveSet",
        // "HotbarCrossActiveSetPvP",
        // "HotbarCrossSetChangeCustomIsAuto",
        // "HotbarCrossSetChangeCustom",
        // "HotbarCrossSetChangeCustomSet1",
        // "HotbarCrossSetChangeCustomSet2",
        // "HotbarCrossSetChangeCustomSet3",
        // "HotbarCrossSetChangeCustomSet4",
        // "HotbarCrossSetChangeCustomSet5",
        // "HotbarCrossSetChangeCustomSet6",
        // "HotbarCrossSetChangeCustomSet7",
        // "HotbarCrossSetChangeCustomSet8",
        // "HotbarCrossSetChangeCustomIsSword",
        // "HotbarCrossSetChangeCustomIsSwordSet1",
        // "HotbarCrossSetChangeCustomIsSwordSet2",
        // "HotbarCrossSetChangeCustomIsSwordSet3",
        // "HotbarCrossSetChangeCustomIsSwordSet4",
        // "HotbarCrossSetChangeCustomIsSwordSet5",
        // "HotbarCrossSetChangeCustomIsSwordSet6",
        // "HotbarCrossSetChangeCustomIsSwordSet7",
        // "HotbarCrossSetChangeCustomIsSwordSet8",
        // "HotbarCrossAdvancedSetting",
        // "HotbarCrossAdvancedSettingLeft",
        // "HotbarCrossAdvancedSettingRight",
        // "HotbarCrossSetPvpModeActive",
        // "HotbarCrossSetChangeCustomPvp",
        // "HotbarCrossSetChangeCustomIsAutoPvp",
        // "HotbarCrossSetChangeCustomSet1Pvp",
        // "HotbarCrossSetChangeCustomSet2Pvp",
        // "HotbarCrossSetChangeCustomSet3Pvp",
        // "HotbarCrossSetChangeCustomSet4Pvp",
        // "HotbarCrossSetChangeCustomSet5Pvp",
        // "HotbarCrossSetChangeCustomSet6Pvp",
        // "HotbarCrossSetChangeCustomSet7Pvp",
        // "HotbarCrossSetChangeCustomSet8Pvp",
        // "HotbarCrossSetChangeCustomIsSwordPvp",
        // "HotbarCrossSetChangeCustomIsSwordSet1Pvp",
        // "HotbarCrossSetChangeCustomIsSwordSet2Pvp",
        // "HotbarCrossSetChangeCustomIsSwordSet3Pvp",
        // "HotbarCrossSetChangeCustomIsSwordSet4Pvp",
        // "HotbarCrossSetChangeCustomIsSwordSet5Pvp",
        // "HotbarCrossSetChangeCustomIsSwordSet6Pvp",
        // "HotbarCrossSetChangeCustomIsSwordSet7Pvp",
        // "HotbarCrossSetChangeCustomIsSwordSet8Pvp",
        // "HotbarCrossAdvancedSettingPvp",
        // "HotbarCrossAdvancedSettingLeftPvp",
        // "HotbarCrossAdvancedSettingRightPvp",

        // "HotbarWXHBEnable",
        // "HotbarWXHBSetLeft",
        // "HotbarWXHBSetRight",
        // "HotbarWXHBEnablePvP",
        // "HotbarWXHBSetLeftPvP",
        // "HotbarWXHBSetRightPvP",
        // "HotbarWXHB8Button",
        // "HotbarWXHB8ButtonPvP",
        // "HotbarWXHBSetInputTime",
        // "HotbarWXHBDisplay",
        // "HotbarWXHBFreeLayout",
        // "HotbarXHBActiveTransmissionAlpha",
        // "HotbarXHBAlphaDefault",
        // "HotbarXHBAlphaActiveSet",
        // "HotbarXHBAlphaInactiveSet",
        // "HotbarWXHBInputOnce",
        "ExHotbarChangeHotbar1IsFashion",
        "HotbarCrossUseExDirectionAutoSwitch",
        "IdlingCameraSwitchType",
        "HotbarXHBEditEnable",
        "HotbarContentsAction2ReverseOperation",
        "HotbarContentsAction2ReturnInitialSlot",
        "HotbarContentsAction2ReverseRotate",
        "PlateType",
        "PlateDispHPBar",
        "PlateDisableMaxHPBar",

        "NamePlateHpSizeType",
        // "NamePlateColorSelf",
        // "NamePlateEdgeSelf",
        "NamePlateDispTypeSelf",
        "NamePlateNameTypeSelf",
        "NamePlateHpTypeSelf",
        // "NamePlateColorSelfBuddy",
        // "NamePlateEdgeSelfBuddy",
        "NamePlateDispTypeSelfBuddy",
        "NamePlateHpTypeSelfBuddy",
        // "NamePlateColorSelfPet",
        // "NamePlateEdgeSelfPet",
        "NamePlateDispTypeSelfPet",
        "NamePlateHpTypeSelfPet",
        // "NamePlateColorParty",
        // "NamePlateEdgeParty",
        "NamePlateDispTypeParty",
        "NamePlateNameTypeParty",
        "NamePlateHpTypeParty",
        "NamePlateDispTypePartyPet",
        "NamePlateHpTypePartyPet",
        "NamePlateDispTypePartyBuddy",
        "NamePlateHpTypePartyBuddy",
        // "NamePlateColorAlliance",
        // "NamePlateEdgeAlliance",
        "NamePlateDispTypeAlliance",
        "NamePlateNameTypeAlliance",
        "NamePlateHpTypeAlliance",
        "NamePlateDispTypeAlliancePet",
        "NamePlateHpTypeAlliancePet",
        // "NamePlateColorOther",
        // "NamePlateEdgeOther",
        "NamePlateDispTypeOther",
        "NamePlateNameTypeOther",
        "NamePlateHpTypeOther",
        "NamePlateDispTypeOtherPet",
        "NamePlateHpTypeOtherPet",
        "NamePlateDispTypeOtherBuddy",
        "NamePlateHpTypeOtherBuddy",
        // "NamePlateColorUnengagedEnemy",
        // "NamePlateEdgeUnengagedEnemy",
        "NamePlateDispTypeUnengagedEnemy",
        "NamePlateHpTypeUnengagedEmemy",
        // "NamePlateColorEngagedEnemy",
        // "NamePlateEdgeEngagedEnemy",
        "NamePlateDispTypeEngagedEnemy",
        "NamePlateHpTypeEngagedEmemy",
        // "NamePlateColorClaimedEnemy",
        // "NamePlateEdgeClaimedEnemy",
        "NamePlateDispTypeClaimedEnemy",
        "NamePlateHpTypeClaimedEmemy",
        // "NamePlateColorUnclaimedEnemy",
        // "NamePlateEdgeUnclaimedEnemy",
        "NamePlateDispTypeUnclaimedEnemy",
        "NamePlateHpTypeUnclaimedEmemy",
        // "NamePlateColorNpc",
        // "NamePlateEdgeNpc",
        "NamePlateDispTypeNpc",
        "NamePlateHpTypeNpc",
        // "NamePlateColorObject",
        // "NamePlateEdgeObject",
        "NamePlateDispTypeObject",
        "NamePlateHpTypeObject",
        // "NamePlateColorMinion",
        // "NamePlateEdgeMinion",
        "NamePlateDispTypeMinion",
        // "NamePlateColorOtherBuddy",
        // "NamePlateEdgeOtherBuddy",
        // "NamePlateColorOtherPet",
        // "NamePlateEdgeOtherPet",
        "NamePlateNameTitleTypeSelf",
        "NamePlateNameTitleTypeParty",
        "NamePlateNameTitleTypeAlliance",
        "NamePlateNameTitleTypeOther",
        "NamePlateNameTitleTypeFriend",
        // "NamePlateColorFriend",
        // "NamePlateColorFriendEdge",
        "NamePlateDispTypeFriend",
        "NamePlateNameTypeFriend",
        "NamePlateHpTypeFriend",
        "NamePlateDispTypeFriendPet",
        "NamePlateHpTypeFriendPet",
        "NamePlateDispTypeFriendBuddy",
        "NamePlateHpTypeFriendBuddy",
        // "NamePlateColorLim",
        // "NamePlateColorLimEdge",
        // "NamePlateColorGri",
        // "NamePlateColorGriEdge",
        // "NamePlateColorUld",
        // "NamePlateColorUldEdge",
        // "NamePlateColorHousingFurniture",
        // "NamePlateColorHousingFurnitureEdge",
        "NamePlateDispTypeHousingFurniture",
        // "NamePlateColorHousingField",
        // "NamePlateColorHousingFieldEdge",
        "NamePlateDispTypeHousingField",
        "NamePlateNameTypePvPEnemy",
        "NamePlateDispTypeFeast",
        "NamePlateNameTypeFeast",
        "NamePlateHpTypeFeast",
        "NamePlateDispTypeFeastPet",
        "NamePlateHpTypeFeastPet",
        "NamePlateNameTitleTypeFeast",
        "NamePlateDispSize",
        "NamePlateDispJobIcon",
        "NamePlateDispJobIconType",
        "NamePlateSetRoleColor",
        // "NamePlateColorTank",
        // "NamePlateEdgeTank",
        // "NamePlateColorHealer",
        // "NamePlateEdgeHealer",
        // "NamePlateColorDps",
        // "NamePlateEdgeDps",
        // "NamePlateColorOtherClass",
        // "NamePlateEdgeOtherClass",
        "NamePlateDispWorldTravel",
        "NamePlateDispJobIconInPublicParty",
        "NamePlateDispJobIconInPublicOther",
        "NamePlateDispJobIconInInstanceParty",
        "NamePlateDispJobIconInInstanceOther",
        "LogNamePlateDispEnemyCast",
        "ActiveInfo",
        "PartyList",
        "PartyListStatus",
        "PartyListStatusTimer",
        "EnemyList",
        "TargetInfo",
        "Gil",
        "DTR",
        "PlayerInfo",
        "NaviMap",
        "Help",
        "CrossMainHelp",
        "HousingLocatePreview",
        "Log",
        "LogTell",
        "LogFontSize",
        "LogTabFilter0",
        "LogTabFilter1",
        "LogTabFilter2",
        "LogTabFilter3",
        "LogChatFilter",
        "LogEnableErrMsgLv1",
        "LogNameType",
        "LogTimeDisp",
        "LogTimeSettingType",
        "LogTimeDispType",
        "IsLogTell",
        "IsLogParty",
        "LogParty",
        "IsLogAlliance",
        "LogAlliance",
        "IsLogFc",
        "LogFc",
        "IsLogPvpTeam",
        "LogPvpTeam",
        "IsLogLs1",
        "LogLs1",
        "IsLogLs2",
        "LogLs2",
        "IsLogLs3",
        "LogLs3",
        "IsLogLs4",
        "LogLs4",
        "IsLogLs5",
        "LogLs5",
        "IsLogLs6",
        "LogLs6",
        "IsLogLs7",
        "LogLs7",
        "IsLogLs8",
        "LogLs8",
        "IsLogBeginner",
        "LogBeginner",
        "IsLogCwls",
        "IsLogCwls2",
        "IsLogCwls3",
        "IsLogCwls4",
        "IsLogCwls5",
        "IsLogCwls6",
        "IsLogCwls7",
        "IsLogCwls8",
        "LogCwls",
        "LogCwls2",
        "LogCwls3",
        "LogCwls4",
        "LogCwls5",
        "LogCwls6",
        "LogCwls7",
        "LogCwls8",
        "LogRecastActionErrDisp",
        "LogPermeationRate",
        "LogFontSizeForm",
        "LogItemLinkEnableType",
        "LogFontSizeLog2",
        "LogTimeDispLog2",
        "LogPermeationRateLog2",
        "LogFontSizeLog3",
        "LogTimeDispLog3",
        "LogPermeationRateLog3",
        "LogFontSizeLog4",
        "LogTimeDispLog4",
        "LogPermeationRateLog4",
        "LogFlyingHeightMaxErrDisp",
        "LogCrossWorldName",
        "LogDragResize",
        "LogNameIconType",
        "LogDispClassJobName",
        "LogSetRoleColor",
        // "LogColorRoleTank",
        // "LogColorRoleHealer",
        // "LogColorRoleDPS",
        // "LogColorOtherClass",
        "LogChatBubbleEnableChatBubble",
        "LogChatBubbleShowMax",
        "LogChatBubbleShowOwnMessage",
        "LogChatBubbleShowDuringBattle",
        "LogChatBubbleSizeType",
        "LogChatBubbleShowLargePvP",
        "LogChatBubbleShowQuickChat",
        "LogChatBubbleDispRowType",
        "LogChatBubbleSayShowType",
        "LogChatBubbleSayFontColor",
        "LogChatBubbleSayWindowColor",
        "LogChatBubbleYellShowType",
        "LogChatBubbleYellFontColor",
        "LogChatBubbleYellWindowColor",
        "LogChatBubbleShoutShowType",
        "LogChatBubbleShoutFontColor",
        "LogChatBubbleShoutWindowColor",
        "LogChatBubbleTellShowType",
        "LogChatBubbleTellFontColor",
        "LogChatBubbleTellWindowColor",
        "LogChatBubblePartyShowType",
        "LogChatBubblePartyFontColor",
        "LogChatBubblePartyWindowColor",
        "LogChatBubbleAllianceShowType",
        "LogChatBubbleAllianceFontColor",
        "LogChatBubbleAllianceWindowColor",
        "LogChatBubbleFcShowType",
        "LogChatBubbleFcFontColor",
        "LogChatBubbleFcWindowColor",
        "LogChatBubbleBeginnerShowType",
        "LogChatBubbleBeginnerFontColor",
        "LogChatBubbleBeginnerWindowColor",
        "LogChatBubblePvpteamShowType",
        "LogChatBubblePvpteamFontColor",
        "LogChatBubblePvpteamWindowColor",
        "LogChatBubbleLs1ShowType",
        "LogChatBubbleLs1FontColor",
        "LogChatBubbleLs1WindowColor",
        "LogChatBubbleLs2ShowType",
        "LogChatBubbleLs2FontColor",
        "LogChatBubbleLs2WindowColor",
        "LogChatBubbleLs3ShowType",
        "LogChatBubbleLs3FontColor",
        "LogChatBubbleLs3WindowColor",
        "LogChatBubbleLs4ShowType",
        "LogChatBubbleLs4FontColor",
        "LogChatBubbleLs4WindowColor",
        "LogChatBubbleLs5ShowType",
        "LogChatBubbleLs5FontColor",
        "LogChatBubbleLs5WindowColor",
        "LogChatBubbleLs6ShowType",
        "LogChatBubbleLs6FontColor",
        "LogChatBubbleLs6WindowColor",
        "LogChatBubbleLs7ShowType",
        "LogChatBubbleLs7FontColor",
        "LogChatBubbleLs7WindowColor",
        "LogChatBubbleLs8ShowType",
        "LogChatBubbleLs8FontColor",
        "LogChatBubbleLs8WindowColor",
        "LogChatBubbleCwls1ShowType",
        "LogChatBubbleCwls1FontColor",
        "LogChatBubbleCwls1WindowColor",
        "LogChatBubbleCwls2ShowType",
        "LogChatBubbleCwls2FontColor",
        "LogChatBubbleCwls2WindowColor",
        "LogChatBubbleCwls3ShowType",
        "LogChatBubbleCwls3FontColor",
        "LogChatBubbleCwls3WindowColor",
        "LogChatBubbleCwls4ShowType",
        "LogChatBubbleCwls4FontColor",
        "LogChatBubbleCwls4WindowColor",
        "LogChatBubbleCwls5ShowType",
        "LogChatBubbleCwls5FontColor",
        "LogChatBubbleCwls5WindowColor",
        "LogChatBubbleCwls6ShowType",
        "LogChatBubbleCwls6FontColor",
        "LogChatBubbleCwls6WindowColor",
        "LogChatBubbleCwls7ShowType",
        "LogChatBubbleCwls7FontColor",
        "LogChatBubbleCwls7WindowColor",
        "LogChatBubbleCwls8ShowType",
        "LogChatBubbleCwls8FontColor",
        "LogChatBubbleCwls8WindowColor",
        "LogPermeationRateInput",
        "ChatType",
        "ShopSell",

        "ColorSay",
        "ColorShout",
        "ColorTell",
        "ColorParty",
        "ColorAlliance",
        "ColorLS1",
        "ColorLS2",
        "ColorLS3",
        "ColorLS4",
        "ColorLS5",
        "ColorLS6",
        "ColorLS7",
        "ColorLS8",
        "ColorFCompany",
        "ColorPvPGroup",
        "ColorPvPGroupAnnounce",
        "ColorBeginner",
        "ColorEmoteUser",
        "ColorEmote",
        "ColorYell",
        "ColorBeginnerAnnounce",
        "ColorCWLS",
        "ColorCWLS2",
        "ColorCWLS3",
        "ColorCWLS4",
        "ColorCWLS5",
        "ColorCWLS6",
        "ColorCWLS7",
        "ColorCWLS8",
        "ColorAttackSuccess",
        "ColorAttackFailure",
        "ColorAction",
        "ColorItem",
        "ColorCureGive",
        "ColorBuffGive",
        "ColorDebuffGive",
        "ColorEcho",
        "ColorSysMsg",
        "ColorFCAnnounce",
        "ColorSysBattle",
        "ColorSysGathering",
        "ColorSysErr",
        "ColorNpcSay",
        "ColorItemNotice",
        "ColorGrowup",
        "ColorLoot",
        "ColorCraft",
        "ColorGathering",

        "ShopConfirm",
        "ShopConfirmMateria",
        "ShopConfirmExRare",
        "ShopConfirmSpiritBondMax",
        "ItemSortItemCategory",
        "ItemSortEquipLevel",
        "ItemSortItemLevel",
        "ItemSortItemStack",
        "ItemSortTidyingType",
        "ItemNoArmoryMaskOff",
        "ItemInventryStoreEnd",
        "InfoSettingDispWorldNameType",
        "TargetNamePlateNameType",
        "FocusTargetNamePlateNameType",
        "ItemDetailTemporarilySwitch",
        "ItemDetailTemporarilySwitchKey",
        "ItemDetailTemporarilyHide",
        "ItemDetailTemporarilyHideKey",
        "ToolTipDispSize",
        "RecommendLoginDisp",
        "RecommendAreaChangeDisp",
        "PlayGuideLoginDisp",
        "PlayGuideAreaChangeDisp",
        "MapPadOperationYReverse",
        "MapPadOperationXReverse",
        "MapDispSize",
        "FlyTextDispSize",
        "PopUpTextDispSize",
        "DetailDispDelayType",
        "PartyListSortTypeTank",
        "PartyListSortTypeHealer",
        "PartyListSortTypeDps",
        "PartyListSortTypeOther",
        "RatioHpDisp",
        "BuffDispType",
        "ContentsFinderListSortType",
        "ContentsFinderSupplyEnable",
        "EnemyListCastbarEnable",
        "AchievementAppealLoginDisp",
        "ContentsFinderUseLangTypeJA",
        "ContentsFinderUseLangTypeEN",
        "ContentsFinderUseLangTypeDE",
        "ContentsFinderUseLangTypeFR",
        "ItemInventryWindowSizeType",
        "ItemInventryRetainerWindowSizeType",
        "BattleTalkShowFace",
        "BannerContentsDispType",
        "BannerContentsNotice",
        "MipDispType",
        "BannerContentsOrderType",
        "CCProgressAllyFixLeftSide",
        "CCMapAllyFixLeftSide",
        "DispCCCountDown",
        "EmoteTextType",
        "IsEmoteSe",
        "EmoteSeType",
        "PartyFinderNewArrivalDisp",
        "GPoseTargetFilterNPCLookAt",
        "GPoseMotionFilterAction",
        "GPoseRollRotationCameraCorrection",
        "GPoseInitCameraFocus",
        "GposePortraitRotateType",
        "GroupPosePortraitUnlockAspectLimit",
        "GroupPosePortraitButtonType",
        "GroupPoseEyelidTracking",
        "GroupPoseEnableEyelidManulOpening",
        "GroupPoseEyelidOpeningL",
        "GroupPoseEyelidOpeningR",
        "LsListSortPriority",
        "FriendListSortPriority",
        "FriendListFilterType",
        "FriendListSortType",
        "LetterListFilterType",
        "LetterListSortType",
        "ContentsReplayEnable",
        "MouseWheelOperationUp",
        "MouseWheelOperationDown",
        "MouseWheelOperationCtrlUp",
        "MouseWheelOperationCtrlDown",
        "MouseWheelOperationAltUp",
        "MouseWheelOperationAltDown",
        "MouseWheelOperationShiftUp",
        "MouseWheelOperationShiftDown",
        "TelepoTicketUseType",
        "TelepoTicketGilSetting",
        "TelepoCategoryType",
        "HidePcAroundQuestProgressNpc",
        "HidePcAroundQuestProgressNpcIncludeParty",
        "HidePcAroundNpcAccessingQuest",
        "HidePcAroundNpcAccessingQuestIncludeParty",
        "PvPFrontlinesGCFree",

        // uiconfig -> float
        "FirstPersonDefaultYAngle",
        "FirstPersonDefaultZoom",
        "FirstPersonDefaultDistance",
        "ThirdPersonDefaultYAngle",
        "ThirdPersonDefaultZoom",
        "ThirdPersonDefaultDistance",
        "LockonDefaultYAngle",
        "LockonDefaultZoom",

        // Ui -> string
        "LogTabName2",
        "LogTabName3",

        // UiControl -> uint
        "AutoChangePointOfView",
        "KeyboardCameraInterpolationType",
        "KeyboardCameraVerticalInterpolation",
        "PadFpsXReverse",
        "PadFpsYReverse",
        "PadTpsXReverse",
        "PadTpsYReverse",
        "MouseFpsXReverse",
        "MouseFpsYReverse",
        "MouseTpsXReverse",
        "MouseTpsYReverse",
        "MouseCharaViewRotYReverse",
        "MouseCharaViewRotXReverse",
        "MouseCharaViewMoveYReverse",
        "MouseCharaViewMoveXReverse",
        "PADCharaViewRotYReverse",
        "PADCharaViewRotXReverse",
        "PADCharaViewMoveYReverse",
        "PADCharaViewMoveXReverse",
        "FlyingControlType",
        "FlyingLegacyAutorun",
        "AutoFaceTargetOnAction",
        "SelfClick",
        "NoTargetClickCancel",
        "AutoTarget",
        "TargetTypeSelect",
        "AutoLockOn",
        "CircleBattleModeAutoChange",
        "CircleIsCustom",
        "CircleSwordDrawnIsActive",
        "CircleSwordDrawnNonPartyPc",
        "CircleSwordDrawnParty",
        "CircleSwordDrawnEnemy",
        "CircleSwordDrawnAggro",
        "CircleSwordDrawnNpcOrObject",
        "CircleSwordDrawnMinion",
        "CircleSwordDrawnDutyEnemy",
        "CircleSwordDrawnPet",
        "CircleSwordDrawnAlliance",
        "CircleSwordDrawnMark",
        "CircleSheathedIsActive",
        "CircleSheathedNonPartyPc",
        "CircleSheathedParty",
        "CircleSheathedEnemy",
        "CircleSheathedAggro",
        "CircleSheathedNpcOrObject",
        "CircleSheathedMinion",
        "CircleSheathedDutyEnemy",
        "CircleSheathedPet",
        "CircleSheathedAlliance",
        "CircleSheathedMark",
        "CircleClickIsActive",
        "CircleClickNonPartyPc",
        "CircleClickParty",
        "CircleClickEnemy",
        "CircleClickAggro",
        "CircleClickNpcOrObject",
        "CircleClickMinion",
        "CircleClickDutyEnemy",
        "CircleClickPet",
        "CircleClickAlliance",
        "CircleClickMark",
        "CircleXButtonIsActive",
        "CircleXButtonNonPartyPc",
        "CircleXButtonParty",
        "CircleXButtonEnemy",
        "CircleXButtonAggro",
        "CircleXButtonNpcOrObject",
        "CircleXButtonMinion",
        "CircleXButtonDutyEnemy",
        "CircleXButtonPet",
        "CircleXButtonAlliance",
        "CircleXButtonMark",
        "CircleYButtonIsActive",
        "CircleYButtonNonPartyPc",
        "CircleYButtonParty",
        "CircleYButtonEnemy",
        "CircleYButtonAggro",
        "CircleYButtonNpcOrObject",
        "CircleYButtonMinion",
        "CircleYButtonDutyEnemy",
        "CircleYButtonPet",
        "CircleYButtonAlliance",
        "CircleYButtonMark",
        "CircleBButtonIsActive",
        "CircleBButtonNonPartyPc",
        "CircleBButtonParty",
        "CircleBButtonEnemy",
        "CircleBButtonAggro",
        "CircleBButtonNpcOrObject",
        "CircleBButtonMinion",
        "CircleBButtonDutyEnemy",
        "CircleBButtonPet",
        "CircleBButtonAlliance",
        "CircleBButtonMark",
        "CircleAButtonIsActive",
        "CircleAButtonNonPartyPc",
        "CircleAButtonParty",
        "CircleAButtonEnemy",
        "CircleAButtonAggro",
        "CircleAButtonNpcOrObject",
        "CircleAButtonMinion",
        "CircleAButtonDutyEnemy",
        "CircleAButtonPet",
        "CircleAButtonAlliance",
        "CircleAButtonMark",
        "GroundTargetType",
        "GroundTargetCursorSpeed",
        "TargetCircleType",
        "TargetLineType",
        "LinkLineType",
        "ObjectBorderingType",
        "MoveMode",
        "HotbarDisp",
        "HotbarEmptyVisible",
        "HotbarNoneSlotDisp01",
        "HotbarNoneSlotDisp02",
        "HotbarNoneSlotDisp03",
        "HotbarNoneSlotDisp04",
        "HotbarNoneSlotDisp05",
        "HotbarNoneSlotDisp06",
        "HotbarNoneSlotDisp07",
        "HotbarNoneSlotDisp08",
        "HotbarNoneSlotDisp09",
        "HotbarNoneSlotDisp10",
        "HotbarNoneSlotDispEX",
        "ExHotbarSetting",
        "HotbarExHotbarUseSetting",
        "HotbarCrossUseEx",
        "HotbarCrossUseExDirection",
        "HotbarCrossDispType",
        "PartyListSoloOff",
        "HowTo",
        "HousingFurnitureBindConfirm",
        "DirectChat",
        "CharaParamDisp",
        "LimitBreakGaugeDisp",
        "ScenarioTreeDisp",
        "ScenarioTreeCompleteDisp",
        "HotbarCrossDispAlways",
        "ExpDisp",
        "InventryStatusDisp",
        "DutyListDisp",
        "NaviMapDisp",
        "GilStatusDisp",
        "InfoSettingDisp",
        "InfoSettingDispType",
        "TargetInfoDisp",
        "EnemyListDisp",
        "FocusTargetDisp",
        "ItemDetailDisp",
        "ActionDetailDisp",
        "DetailTrackingType",
        "ToolTipDisp",
        "MapPermeationRate",
        "MapOperationType",
        "PartyListDisp",
        "PartyListNameType",
        "FlyTextDisp",
        "MapPermeationMode",
        "AllianceList1Disp",
        "AllianceList2Disp",
        "TargetInfoSelfBuff",
        "PopUpTextDisp",
        "ContentsInfoDisp",
        "DutyListHideWhenCntInfoDisp",
        "DutyListNumDisp",
        "InInstanceContentDutyListDisp",
        "InPublicContentDutyListDisp",
        "ContentsInfoJoiningRequestDisp",
        "ContentsInfoJoiningRequestSituationDisp",
        "HotbarDispSetNum",
        "HotbarDispSetChangeType",
        "HotbarDispSetDragType",
        "MainCommandType",
        "MainCommandDisp",
        "MainCommandDragShortcut",
        "HotbarDispLookNum",

        // UiControl -> float
        "TiltOffset",
        "KeyboardSpeed",
        "PadSpeed"
};
}

public enum SettingsDisplayObjectLimitType {
    Automatic = 0,
    Maximum = 1,
    High = 2,
    Normal = 3,
    Low = 4,
    Minimum = 5
}
