//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterOfPuppets.Resources;

using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Language {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Language() {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterOfPuppets.Resources.Language", typeof(Language).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }

    internal static string SettingsWindowAllowCloseWithEscape {
        get {
            return ResourceManager.GetString("SettingsWindowAllowCloseWithEscape", resourceCulture);
        }
    }

    internal static string SettingsWindowAllowMovement {
        get {
            return ResourceManager.GetString("SettingsWindowAllowMovement", resourceCulture);
        }
    }
    internal static string SettingsWindowAllowResize {
        get {
            return ResourceManager.GetString("SettingsWindowAllowResize", resourceCulture);
        }
    }

    internal static string SettingsWindowOpenLogin {
        get {
            return ResourceManager.GetString("SettingsWindowOpenLogin", resourceCulture);
        }
    }

    internal static string SettingsWindowShowConfigButton {
        get {
            return ResourceManager.GetString("SettingsWindowShowConfigButton", resourceCulture);
        }
    }

    internal static string SettingsTitle {
        get {
            return ResourceManager.GetString("SettingsTitle", resourceCulture);
        }
    }
    internal static string MacroEditorTitle {
        get {
            return ResourceManager.GetString("MacroEditorTitle", resourceCulture);
        }
    }
    internal static string AddMacroBtn {
        get {
            return ResourceManager.GetString("AddMacroBtn", resourceCulture);
        }
    }
    internal static string EditMacroBtn {
        get {
            return ResourceManager.GetString("EditMacroBtn", resourceCulture);
        }
    }
    internal static string DeleteInstructionTooltip {
        get {
            return ResourceManager.GetString("DeleteInstructionTooltip", resourceCulture);
        }
    }
    internal static string DeleteSelectedMacrosBtn {
        get {
            return ResourceManager.GetString("DeleteSelectedMacrosBtn", resourceCulture);
        }
    }
    internal static string SaveMacroBtn {
        get {
            return ResourceManager.GetString("SaveMacroBtn", resourceCulture);
        }
    }
    internal static string RunMacroBtn {
        get {
            return ResourceManager.GetString("RunMacroBtn", resourceCulture);
        }
    }
    internal static string MacroTextInputLabel {
        get {
            return ResourceManager.GetString("MacroTextInputLabel", resourceCulture);
        }
    }
    internal static string CharactersLabel {
        get {
            return ResourceManager.GetString("CharactersLabel", resourceCulture);
        }
    }
    internal static string MacroListTitle {
        get {
            return ResourceManager.GetString("MacroListTitle", resourceCulture);
        }
    }
    internal static string MacroNameLabel {
        get {
            return ResourceManager.GetString("MacroNameLabel", resourceCulture);
        }
    }
    internal static string MacroColorLabel {
        get {
            return ResourceManager.GetString("MacroColorLabel", resourceCulture);
        }
    }
    internal static string MacroTagsLabel {
        get {
            return ResourceManager.GetString("MacroTagsLabel", resourceCulture);
        }
    }
    internal static string MacroIconLabel {
        get {
            return ResourceManager.GetString("MacroIconLabel", resourceCulture);
        }
    }
    internal static string SettingsWindowOpenOnStartup {
        get {
            return ResourceManager.GetString("SettingsWindowOpenOnStartup", resourceCulture);
        }
    }
    internal static string SettingsGeneralTab {
        get {
            return ResourceManager.GetString("SettingsGeneralTab", resourceCulture);
        }
    }
    internal static string CloneMacroBtn {
        get {
            return ResourceManager.GetString("CloneMacroBtn", resourceCulture);
        }
    }
    internal static string StopMacroExecutionBtn {
        get {
            return ResourceManager.GetString("StopMacroExecutionBtn", resourceCulture);
        }
    }
    internal static string StopMovementBtn {
        get {
            return ResourceManager.GetString("StopMovementBtn", resourceCulture);
        }
    }
    internal static string MacroSearchInputLabel {
        get {
            return ResourceManager.GetString("MacroSearchInputLabel", resourceCulture);
        }
    }
    internal static string SearchInputLabel {
        get {
            return ResourceManager.GetString("SearchInputLabel", resourceCulture);
        }
    }
    internal static string ShowMacroQueueBtn {
        get {
            return ResourceManager.GetString("ShowMacroQueueBtn", resourceCulture);
        }
    }
    internal static string ToggleMacroTagsPanelBtn {
        get {
            return ResourceManager.GetString("ToggleMacroTagsPanelBtn", resourceCulture);
        }
    }
    internal static string ShowEmotesBtn {
        get {
            return ResourceManager.GetString("ShowEmotesBtn", resourceCulture);
        }
    }
    internal static string EmotesTitle {
        get {
            return ResourceManager.GetString("EmotesTitle", resourceCulture);
        }
    }
    internal static string MacroQueueTitle {
        get {
            return ResourceManager.GetString("MacroQueueTitle", resourceCulture);
        }
    }
    internal static string MacroImportExportTitle {
        get {
            return ResourceManager.GetString("MacroImportExportTitle", resourceCulture);
        }
    }
    internal static string MacroBatchEditorTitle {
        get {
            return ResourceManager.GetString("MacroBatchEditorTitle", resourceCulture);
        }
    }
    internal static string ShowCharactersBtn {
        get {
            return ResourceManager.GetString("ShowCharactersBtn", resourceCulture);
        }
    }
    internal static string SettingsWindowSaveConfigAfterSync {
        get {
            return ResourceManager.GetString("SettingsWindowSaveConfigAfterSync", resourceCulture);
        }
    }
    internal static string SettingsWindowSyncClients {
        get {
            return ResourceManager.GetString("SettingsWindowSyncClients", resourceCulture);
        }
    }
    internal static string SettingsGameSettingsTab {
        get {
            return ResourceManager.GetString("SettingsGameSettingsTab", resourceCulture);
        }
    }
    internal static string FashionAccessoriesTitle {
        get {
            return ResourceManager.GetString("FashionAccessoriesTitle", resourceCulture);
        }
    }
    internal static string FacewearTitle {
        get {
            return ResourceManager.GetString("FacewearTitle", resourceCulture);
        }
    }
    internal static string MountTitle {
        get {
            return ResourceManager.GetString("MountTitle", resourceCulture);
        }
    }
    internal static string ShowFashionAccessoriesBtn {
        get {
            return ResourceManager.GetString("ShowFashionAccessoriesBtn", resourceCulture);
        }
    }
    internal static string ShowFacewearBtn {
        get {
            return ResourceManager.GetString("ShowFacewearBtn", resourceCulture);
        }
    }
    internal static string ShowMountBtn {
        get {
            return ResourceManager.GetString("ShowMountBtn", resourceCulture);
        }
    }
    internal static string GroupsLabel {
        get {
            return ResourceManager.GetString("GroupsLabel", resourceCulture);
        }
    }
    internal static string MinionTitle {
        get {
            return ResourceManager.GetString("MinionTitle", resourceCulture);
        }
    }
    internal static string ShowMinionBtn {
        get {
            return ResourceManager.GetString("ShowMinionBtn", resourceCulture);
        }
    }
    internal static string ShowItemBtn {
        get {
            return ResourceManager.GetString("ShowItemBtn", resourceCulture);
        }
    }
    internal static string ItemTitle {
        get {
            return ResourceManager.GetString("ItemTitle", resourceCulture);
        }
    }
    internal static string GearSetTitle {
        get {
            return ResourceManager.GetString("GearSetTitle", resourceCulture);
        }
    }
    internal static string ShowMacroHelpBtn {
        get {
            return ResourceManager.GetString("ShowMacroHelpBtn", resourceCulture);
        }
    }
    internal static string ActionsTitle {
        get {
            return ResourceManager.GetString("ActionsTitle", resourceCulture);
        }
    }
    internal static string OpenPluginFolder {
        get {
            return ResourceManager.GetString("OpenPluginFolder", resourceCulture);
        }
    }
    internal static string OpenPluginConfigFile {
        get {
            return ResourceManager.GetString("OpenPluginConfigFile", resourceCulture);
        }
    }
    internal static string SettingsWindowUseChatSync {
        get {
            return ResourceManager.GetString("SettingsWindowUseChatSync", resourceCulture);
        }
    }
    internal static string SettingsChatSyncTab {
        get {
            return ResourceManager.GetString("SettingsChatSyncTab", resourceCulture);
        }
    }
    internal static string ExportMacroBtn {
        get {
            return ResourceManager.GetString("ExportMacroBtn", resourceCulture);
        }
    }
    internal static string ImportMacroBtn {
        get {
            return ResourceManager.GetString("ImportMacroBtn", resourceCulture);
        }
    }
    internal static string SettingsWindowUseChatCommandSenderWhitelist {
        get {
            return ResourceManager.GetString("SettingsWindowUseChatCommandSenderWhitelist", resourceCulture);
        }
    }
    internal static string SettingsWindowDefaultChatSyncPrefix {
        get {
            return ResourceManager.GetString("SettingsWindowDefaultChatSyncPrefix", resourceCulture);
        }
    }
    internal static string ClipboardCopyMessage {
        get {
            return ResourceManager.GetString("ClipboardCopyMessage", resourceCulture);
        }
    }
    internal static string RemoveAllBtn {
        get {
            return ResourceManager.GetString("RemoveAllBtn", resourceCulture);
        }
    }
    internal static string SettingsWindowAutoSaveMacro {
        get {
            return ResourceManager.GetString("SettingsWindowAutoSaveMacro", resourceCulture);
        }
    }
    internal static string DismissBtn {
        get {
            return ResourceManager.GetString("DismissBtn", resourceCulture);
        }
    }
    internal static string ClickToExecute {
        get {
            return ResourceManager.GetString("ClickToExecute", resourceCulture);
        }
    }
    internal static string ClickToCopy {
        get {
            return ResourceManager.GetString("ClickToCopy", resourceCulture);
        }
    }
    internal static string MacroExportPath {
        get {
            return ResourceManager.GetString("MacroExportPath", resourceCulture);
        }
    }
    internal static string MacroBackup {
        get {
            return ResourceManager.GetString("MacroBackup", resourceCulture);
        }
    }
}

